package generator

import (
	"bytes"
	"strings"
	"text/template"

	"github.com/khan-rasul/flagctl/pkg/config"
)

type GoGenerator struct{}

func (g *GoGenerator) Language() string {
	return "go"
}

func toPascalCase(key string) string {
	parts := strings.FieldsFunc(key, func(r rune) bool {
		return r == '-' || r == '_' || r == '.' || r == '/'
	})
	for i := range parts {
		if len(parts[i]) > 0 {
			parts[i] = strings.ToUpper(parts[i][:1]) + strings.ToLower(parts[i][1:])
		}
	}
	return strings.Join(parts, "")
}

type goFlagModel struct {
	Key          string
	MethodName   string
	GoType       string
	SDKMethod    string
	DefaultValue string
	Description  string
}

const goTemplate = `// Code generated by flagctl 0.0.1; DO NOT EDIT.
package flags

import (
	"context"
)

type EvaluationClient interface {
	BooleanValue(ctx context.Context, flag string, defaultValue bool, evalCtx map[string]interface{}) (bool, error)
	StringValue(ctx context.Context, flag string, defaultValue string, evalCtx map[string]interface{}) (string, error)
	FloatValue(ctx context.Context, flag string, defaultValue float64, evalCtx map[string]interface{}) (float64, error)
}

{{- range .Flags }}

// {{ .MethodName }} {{ .Description }}
func {{ .MethodName }}(ctx context.Context, client EvaluationClient, evalCtx map[string]interface{}) ({{ .GoType }}, error) {
	return client.{{ .SDKMethod }}(ctx, "{{ .Key }}", {{ .DefaultValue }}, evalCtx)
}
{{- end }}
`

func (g *GoGenerator) Generate(cfg *config.FlagConfig) (string, error) {
	var models []goFlagModel

	for key, flag := range cfg.Flags {
		t := inferType(flag)
		desc := ""
		if flag.Metadata != nil {
			if d, ok := flag.Metadata["description"].(string); ok {
				desc = d
			}
		}
		if desc == "" {
			desc = "evaluates feature flag " + key
		}

		goType := "bool"
		sdkMethod := "BooleanValue"
		defVal := "false"

		if t == "string" {
			goType = "string"
			sdkMethod = "StringValue"
			defVal = `""`
			if flag.DefaultVariant != "" {
				if v, ok := flag.Variants[flag.DefaultVariant].(string); ok {
					defVal = `"` + v + `"`
				}
			}
		} else if t == "number" {
			goType = "float64"
			sdkMethod = "FloatValue"
			defVal = "0.0"
		} else if t == "boolean" {
			if flag.DefaultVariant != "" {
				if b, ok := flag.Variants[flag.DefaultVariant].(bool); ok && b {
					defVal = "true"
				}
			}
		}

		models = append(models, goFlagModel{
			Key:          key,
			MethodName:   toPascalCase(key),
			GoType:       goType,
			SDKMethod:    sdkMethod,
			DefaultValue: defVal,
			Description:  desc,
		})
	}

	tmpl, err := template.New("go").Parse(goTemplate)
	if err != nil {
		return "", err
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, map[string]interface{}{"Flags": models}); err != nil {
		return "", err
	}

	return buf.String(), nil
}
