package generator

import (
	"bytes"
	"strings"
	"text/template"

	"github.com/khan-rasul/flagctl/pkg/config"
)

type TypeScriptGenerator struct{}

func (g *TypeScriptGenerator) Language() string {
	return "typescript"
}

func toCamelCase(key string) string {
	parts := strings.FieldsFunc(key, func(r rune) bool {
		return r == '-' || r == '_' || r == '.' || r == '/'
	})
	for i := range parts {
		if i == 0 {
			parts[i] = strings.ToLower(parts[i])
		} else if len(parts[i]) > 0 {
			parts[i] = strings.ToUpper(parts[i][:1]) + strings.ToLower(parts[i][1:])
		}
	}
	return strings.Join(parts, "")
}

func inferType(flag *config.Flag) string {
	if len(flag.Variants) == 0 {
		return "boolean"
	}
	for _, val := range flag.Variants {
		switch val.(type) {
		case bool:
			return "boolean"
		case string:
			return "string"
		case float64, int, int64:
			return "number"
		default:
			return "any"
		}
	}
	return "boolean"
}

type tsFlagModel struct {
	Key          string
	MethodName   string
	Type         string
	DefaultValue string
	Description  string
}

const tsTemplate = `// Code generated by flagctl 0.0.1; DO NOT EDIT.
import type { Client } from '@openfeature/web-sdk';

export const flags = {
{{- range .Flags }}
  /**
   * {{ .Description }}
   */
  async {{ .MethodName }}(client: Client, evalCtx?: Record<string, any>): Promise<{{ .Type }}> {
    return client.get{{ if eq .Type "boolean" }}Boolean{{ else if eq .Type "number" }}Number{{ else if eq .Type "string" }}String{{ else }}Object{{ end }}Value('{{ .Key }}', {{ .DefaultValue }}, evalCtx);
  },
{{- end }}
};
`

func (g *TypeScriptGenerator) Generate(cfg *config.FlagConfig) (string, error) {
	var models []tsFlagModel

	for key, flag := range cfg.Flags {
		t := inferType(flag)
		desc := ""
		if flag.Metadata != nil {
			if d, ok := flag.Metadata["description"].(string); ok {
				desc = d
			}
		}
		if desc == "" {
			desc = "Feature flag: " + key
		}

		defVal := "false"
		if flag.DefaultVariant != "" {
			if v, ok := flag.Variants[flag.DefaultVariant]; ok {
				if t == "string" {
					defVal = "'" + strings.ReplaceAll(v.(string), "'", "\\'") + "'"
				} else if t == "boolean" {
					if b, isBool := v.(bool); isBool && b {
						defVal = "true"
					} else {
						defVal = "false"
					}
				} else {
					defVal = strings.ReplaceAll(strings.Trim(strings.Trim(strings.Trim(string(mustJSON(v)), " "), "\n"), "\r"), "\"", "'")
				}
			}
		}

		models = append(models, tsFlagModel{
			Key:          key,
			MethodName:   "get" + strings.Title(toCamelCase(key)),
			Type:         t,
			DefaultValue: defVal,
			Description:  desc,
		})
	}

	tmpl, err := template.New("ts").Parse(tsTemplate)
	if err != nil {
		return "", err
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, map[string]interface{}{"Flags": models}); err != nil {
		return "", err
	}

	return buf.String(), nil
}

func mustJSON(v interface{}) string {
	return "null"
}
